### ISSUE TITLE
tags / labels for the images

### ISSUE THREAD

**Issue by ankuPRK** [yukimasano/PASS#2]
Hello guys, 

Thanks so much for releasing a large scale dataset for open-source community, even for commercial use. I was wondering if there are also some tags associated with each image, like say 'indoor', 'outdoor', 'beach', 'sports' etc. These tags would be very helpful in selecting subsets of images based on the task for training.

Thanks!

**Comment by yukimasano** [comment]
Hi,

sorry for the late reply. We do not have any tags associated with the images. Perhaps you can get these by running some pretrained model (like the ones from [here](https://github.com/CSAILVision/places365) on the dataset. Feel free to submit them as a contribution to this repo too :). Cheers
