### ISSUE TITLE
Part 3, 4 are missing

### ISSUE THREAD

**Issue by junhsss** [yukimasano/PASS#3]
Hello @yukimasano! 👋🏻

I was trying to download the dataset, but found part 3 and 4 were missing. I guess I can download the images from the AWS url but I prefer to download them in zip files. Would you mind uploading the missing parts? 

Thanks so much for sharing this amazing dataset!

**Comment by yukimasano** [comment]
Dear @junhsss, I've fixed it. Thank you for letting me know! 
https://zenodo.org/record/6615455
