### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by 99991** [yukimasano/PASS#4]
Thank you for this amazing dataset!

I have two questions about the licenses.

1. The file `pass_metadata.csv` contains the value `Attribution License`, for example in the second line in column "licensename" looks like this: `3,quinnums,2004-05-17 00:44:29.0,Attribution License,21657882a4c879e3d08bf7eb59974515`. I found [the source of the image](https://www.flickr.com/photos/quinn/34669) by searching for the hash using Google and the image appears to be licensed under the [CC-BY 2.0 license](https://creativecommons.org/licenses/by/2.0/legalcode). Does `Attribution License` always correspond to this version of CC-BY or are other versions or even other licenses possible as well?
2. The CC-BY 2.0 license says:

> If you distribute, publicly display, publicly perform, or publicly digitally perform the Work or any Derivative Works or Collective Works, **You must keep intact** all copyright notices for the Work and give the Original Author credit reasonable to the medium or means You are utilizing by conveying the name (or pseudonym if applicable) of the Original Author if supplied; the title of the Work if supplied; to the extent reasonably practicable, **the Uniform Resource Identifier**, if any, that Licensor specifies to be associated with the Work, unless such URI does not refer to the copyright notice or licensing information for the Work;

Where can I find the URL for each image so I can attribute the authors as required by the license? For example, the image mentioned above has the URL https://www.flickr.com/photos/quinn/34669

As an aside, I looked at a few random images in `PASS.0.tar` and found two images with people in them:

* `PASS_dataset/18/7f8182d7e7c8b6b7cf487850974aafbd.jpg` (person with closed eyes, probably an advertisement poster)
* `PASS_dataset/13/8392afd3b652b62133b199a8ee82e39.jpg` (black-and-white photo of a person sitting in a car, half of the face is hidden. Another unrecognizable person can be seen in the car's reflection)

I also tried to find more images with humans using https://github.com/rom1504/clip-retrieval but https://github.com/mlfoundations/open_clip but mostly found false positives, so unfortunately I can not offer an automated way to find more humans in this dataset.

**Comment by yukimasano** [comment]
Hi there!
Thanks so much for your interest and the questions and sorry the late reply. 
All the images in the dataset are of CC-BY Attribution Licence. I'm not sure but some might be CC-BY 3.0 or 4.0 instead, but all are Attribution Licence, that we made sure of.

Thanks for those images. I've noted them down -- note that I keep updating the dataset (now on it's 3rd version) everytime I remove a few more images that people like you have spotted. PS: a nice tool is also google's know-your-data, at least for public datasets. Let me know if there's anything else I can help with. Yuki

**Comment by 99991** [comment]
Hi!

https://knowyourdata-tfds.withgoogle.com/#dataset=pass is very cool. Thanks for pointing out this useful website!

I am still trying to find the attribution information for the individual images. So far, I found [this sqlite3 database](https://multimedia-commons.s3-us-west-2.amazonaws.com/tools/etc/yfcc100m_dataset.sql) from [this issue](https://github.com/openai/CLIP/issues/50#issuecomment-1051348443). The database contains the attribution information, but I can not match them to the correct image.

For example, I have the image `PASS_dataset/7/d37c5aaffa6bd2992b576f6d88678d1.jpg` from `PASS.9.tar` downloaded from https://zenodo.org/record/6615455

To comply with the attribution instructions of the CC BY license, I must provide the URL https://www.flickr.com/photos/61685594@N00/1474437500 but it is not clear how to get the URL from the file name.

Using the file name, I can find the image in [Know Your Data](https://knowyourdata-tfds.withgoogle.com/#dataset=pass&filters=default_segment.pass.image_hash.value:d37c5aaffa6bd2992b576f6d88678d1&tab=ITEM&item=train%5B366shard%5D_718), but the required information is missing, so that seems like a dead end.

The closest I got so far is to use `grep` to find the correct line to some file in `pass_metadata.csv`. This way, I get the username (`unickname`) `AndWat` and the date the photo was taken (`datetaken`) `2007-09-25 19:39:03.0`.

```
grep d37c5aaffa6bd2992b576f6d88678d1 pass_metadata.csv
1951777,AndWat,2007-09-25 19:39:03.0,Attribution License,d37c5aaffa6bd2992b576f6d88678d1,,
```

I can then use the username and date to get matching images from the sqlite3 database (much faster with index).

```
sqlite3 yfcc100m_dataset.sql
create index unickname_index on yfcc100m_dataset (unickname);
select * from yfcc100m_dataset where unickname = 'AndWat' and datetaken = '2007-09-25 19:39:03.0';
1474437500|61685594@N00|AndWat|2007-09-25 19:39:03.0|1191377407|Canon+PowerShot+A540|Banana+Penguin|Note+the+egg.|banana,penguin|||||http://www.flickr.com/photos/61685594@N00/1474437500/|http://farm2.staticflickr.com/1436/1474437500_6e440ad92f.jpg|Attribution License|http://creativecommons.org/licenses/by/2.0/|1436|2|6e440ad92f|0c94c0d602|jpg|0
```

The query result contains the correct license (CC BY 2.0 in this case) and the URL I want: https://www.flickr.com/photos/61685594@N00/1474437500

Unfortunately, this procedure does not always work because `datetaken` is inaccurate. For example, the following query returns 6 rows, so it is not possible to match the image files to the correct URL.

```
select * from yfcc100m_dataset where unickname = 'alykat' and datetaken = '2004-03-13 23:06:52.0';
9851241|80081757@N00|alykat|2004-03-13 23:06:52.0|1113880012||Reflections|A+glass+building+along+Baltimore%27s+Inner+Harbor.|baltimore,glass,innerharbor,reflection||-76.612386|39.28473|16|http://www.flickr.com/photos/80081757@N00/9851241/|http://farm1.staticflickr.com/6/9851241_748a80dd14.jpg|Attribution License|http://creativecommons.org/licenses/by/2.0/|6|1|748a80dd14|748a80dd14|jpg|0
9851242|80081757@N00|alykat|2004-03-13 23:06:52.0|1113880012||Sea+Gull||baltimore,bird,innerharbor,one,rocks,seagull||-76.612762|39.28215|16|http://www.flickr.com/photos/80081757@N00/9851242/|http://farm1.staticflickr.com/5/9851242_a26d9ceda5.jpg|Attribution License|http://creativecommons.org/licenses/by/2.0/|5|1|a26d9ceda5|a26d9ceda5|jpg|0
9851243|80081757@N00|alykat|2004-03-13 23:06:52.0|1113880012||Illumination||baltimore,innerharbor,lamp,light||-76.612762|39.28215|16|http://www.flickr.com/photos/80081757@N00/9851243/|http://farm1.staticflickr.com/7/9851243_69fce61c15.jpg|Attribution License|http://creativecommons.org/licenses/by/2.0/|7|1|69fce61c15|69fce61c15|jpg|0
9851244|80081757@N00|alykat|2004-03-13 23:06:52.0|1113880012||Elementary|Elements+on+display+at+the+Maryland+Science+Museum+in+Baltimore.|baltimore,innerharbor,science||-76.612762|39.28215|16|http://www.flickr.com/photos/80081757@N00/9851244/|http://farm1.staticflickr.com/8/9851244_106a40fe02.jpg|Attribution License|http://creativecommons.org/licenses/by/2.0/|8|1|106a40fe02|106a40fe02|jpg|0
9851245|80081757@N00|alykat|2004-03-13 23:06:52.0|1113880012||Caution||baltimore,caution,innerharbor,sign||-76.607408|39.282264|16|http://www.flickr.com/photos/80081757@N00/9851245/|http://farm1.staticflickr.com/8/9851245_d89dbf7437.jpg|Attribution License|http://creativecommons.org/licenses/by/2.0/|8|1|d89dbf7437|d89dbf7437|jpg|0
9851246|80081757@N00|alykat|2004-03-13 23:06:52.0|1113880012||Coast+Guard|A+Coast+Guard+ship+docked+at+Baltimore%27s+Inner+Harbor.|baltimore,boar,coastguard,innerharbor,ship||-76.611142|39.285569|16|http://www.flickr.com/photos/80081757@N00/9851246/|http://farm1.staticflickr.com/7/9851246_7ec2f4bd28.jpg|Attribution License|http://creativecommons.org/licenses/by/2.0/|7|1|7ec2f4bd28|7ec2f4bd28|jpg|0
```

Maybe it is possible using the hashes somehow, but I do not know how they were derived. The integer `d37c5aaffa6bd2992b576f6d88678d1` has a length of 124 bits, which is a weird size (perhaps truncated?) The Flickr hashes should be randomly generated for security reasons, so they can probably not help us.

Do you have an idea how to map the file names to URLs correctly?

**Comment by yukimasano** [comment]
Hi, in the case of `PASS_dataset/7/d37c5aaffa6bd2992b576f6d88678d1.jpg`, the `d37c5aaffa6bd2992b576f6d88678d1` should correspond to the `photoid` (or `photohash`) column of the sqlite3 database. Let me know if this isn't the case/ doesn't work!

**Comment by 99991** [comment]
Hi, unfortunately the `photoid` column of the sqlite3 database is a relatively small integer, not a hash. Here is the query with headers, although there is no column which contains a 124 bit hash.

```
sqlite3 yfcc100m_dataset.sql
.header on
select * from yfcc100m_dataset where unickname = 'AndWat' and datetaken = '2007-09-25 19:39:03.0';

photoid|uid|unickname|datetaken|dateuploaded|capturedevice|title|description|usertags|machinetags|longitude|latitude|accuracy|pageurl|downloadurl|licensename|licenseurl|serverid|farmid|secret|secretoriginal|ext|marker
1474437500|61685594@N00|AndWat|2007-09-25 19:39:03.0|1191377407|Canon+PowerShot+A540|Banana+Penguin|Note+the+egg.|banana,penguin|||||http://www.flickr.com/photos/61685594@N00/1474437500/|http://farm2.staticflickr.com/1436/1474437500_6e440ad92f.jpg|Attribution License|http://creativecommons.org/licenses/by/2.0/|1436|2|6e440ad92f|0c94c0d602|jpg|0
```

I also checked whether the `photoid` of the sqlite3 table matches the first unnamed column of the `pass_metadata.csv` file, but it seems that they do not.

**Comment by yukimasano** [comment]
Hi, I think this should now solve it ;) `https://www.robots.ox.ac.uk/~vgg/data/pass/pass_v3_meta_with_url.csv` (~230MB)

**Comment by 99991** [comment]
> Hi, I think this should now solve it ;)

Yes, it does! Thank you!
