### ISSUE TITLE
Miss cascade_rcnn pickle in person detector

### ISSUE THREAD

**Issue by realliyifei** [yukimasano/PASS#6]
No cascade\_rcnn.pkl checkpoint found when implementing person\_detector.py

"/scratch/shared/beegfs/yuki/adiwol/experts/cascade\_rcnn.pkl" 

Is this missed in the repo?

**Comment by yukimasano** [comment]
Hi, sorry for this. 
We use a COCO trained cascade_rcnn from the detectron2 repo: 
https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md#other-settings 

More specifically:
https://dl.fbaipublicfiles.com/detectron2/Misc/cascade_mask_rcnn_R_50_FPN_3x/144998488/model_final_480dd8.pkl

**Comment by realliyifei** [comment]
thanks! glad that I used the same one :smile:
