### ISSUE TITLE
Distribution of places

### ISSUE THREAD

**Issue by GeekAlexis** [yukimasano/PASS#7]
Hi,

Would it be possible to release the distribution of places (figure in paper) that shows specific place categories? We are interested to see if PASS contains more outdoor scenes than ImageNet-1K. 

If not, can you point me toward which pretrained place-365 CNN you used to extract the distribution? Thanks!

**Comment by yukimasano** [comment]
Hi there,
I've used the pretrained models from here the original authors from here: https://github.com/CSAILVision/places365
Perhaps CLIP's zero-shot accuracy is also good, they don't report it in the paper, but have good numbers on SUN, so perhaps also worth a try ;).
