### ISSUE TITLE
human in PASS

### ISSUE THREAD

**Issue by iperov** [yukimasano/PASS#9]
your statement is
_Our dataset does not include any identifiable humans._

but 

01b9bd7d07884465f44c2fa8ba46b85.jpg
![01b9bd7d07884465f44c2fa8ba46b85](https://github.com/user-attachments/assets/4dabc7c2-a354-413e-b831-e4d3288ac031)

**Comment by yukimasano** [comment]
Hi, 
I'm pretty (90%) sure that this is a statue. The reflection on the face and the pigeons would point to this.
It might be an identifiable _statue_, but it's not a human.

**Comment by iperov** [comment]
it's identificable as human face.
So your dataset is not suitable for human or face related tasks where background must contain nothing similar to human or human face.

**Comment by yukimasano** [comment]
Yes, though the number should be quite low because of our automated and
human pipeline.
